# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: /go/src/github.com/RedisGraph/redisgraph-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: |
          docker run -d -p 6379:6379 -it --rm --name redisgraph redislabs/redisgraph:edge
          go test -v ./...
